language: node_js
node_js:
  - "6"
  - "8"
  - "10"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y hunspell

notifications:
  slack: 'inist-dpi:53Jp5iUZeRidSGZn0TukMSKo#activity'
